//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhimNosime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.TAP_PHIM = new HashSet<TAP_PHIM>();
            this.BOOKMARKs = new HashSet<BOOKMARK>();
            this.LS_XEM = new HashSet<LS_XEM>();
        }
    
        public int ID_PHIM { get; set; }
        public string TITLE_PHIM { get; set; }
        public string TEN_PHIM { get; set; }
        public string THE_LOAI { get; set; }
        public string QUOC_GIA { get; set; }
        public string DAO_DIEN { get; set; }
        public string NAM_SX { get; set; }
        public Nullable<int> DANH_GIA { get; set; }
        public string DEC { get; set; }
        public string IMG_PHIM { get; set; }
        public string IMG_BG { get; set; }
        public string DVIEN { get; set; }
        public int ID_TAG { get; set; }
        public int ID_SUBTAG { get; set; }
    
        public virtual SUBTAG SUBTAG { get; set; }
        public virtual TAG TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAP_PHIM> TAP_PHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKMARK> BOOKMARKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LS_XEM> LS_XEM { get; set; }
    }
}
