//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhimNosime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAP_PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAP_PHIM()
        {
            this.LS_XEM = new HashSet<LS_XEM>();
        }
    
        public int ID_TAP { get; set; }
        public string TAP { get; set; }
        public int ID_PHIM { get; set; }
        public string MA_TAP { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LS_XEM> LS_XEM { get; set; }
    }
}
