//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhimNosime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAPPHIM_PHIM
    {
        public string TITLE_PHIM { get; set; }
        public string TEN_PHIM { get; set; }
        public string THE_LOAI { get; set; }
        public string QUOC_GIA { get; set; }
        public string DAO_DIEN { get; set; }
        public string NAM_SX { get; set; }
        public Nullable<int> DANH_GIA { get; set; }
        public string DEC { get; set; }
        public string IMG_PHIM { get; set; }
        public string IMG_BG { get; set; }
        public string TAP { get; set; }
        public string MA_TAP { get; set; }
    }
}
