//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhimNosime.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebPhimDBContext : DbContext
    {
        public WebPhimDBContext()
            : base("name=WebPhimDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<SUBTAG> SUBTAGs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAG> TAGs { get; set; }
        public virtual DbSet<TAP_PHIM> TAP_PHIM { get; set; }
        public virtual DbSet<TAPPHIM_PHIM> TAPPHIM_PHIM { get; set; }
        public virtual DbSet<BOOKMARK> BOOKMARKs { get; set; }
        public virtual DbSet<LS_XEM> LS_XEM { get; set; }
    }
}
